# Generated by Django 5.2.7 on 2025-12-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentsample',
            name='size_cen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='size_cen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
