# Generated by Django 5.2.7 on 2025-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_manager', '0003_garmentsample_gsm_garmentsample_size_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentsample',
            name='category',
            field=models.CharField(blank=True, choices=[('CIRCULAR_KNIT', 'Circular Knit'), ('FLAT_KNIT', 'Flat Knit'), ('WOVEN', 'Woven')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='garmentsample',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('MENS', 'Mens'), ('JR_LADIES', 'Jr. Ladies'), ('WOMEN', 'Women'), ('JUNIOR_BOYS', 'Junior Boys'), ('SENIOR_BOYS', 'Senior Boys'), ('TODDLER_BOYS', 'Toddler Boys'), ('JUNIOR_GIRLS', 'Junior Girls'), ('SENIOR_GIRLS', 'Senior Girls'), ('TODDLER_GIRLS', 'Toddler Girls'), ('KIDS', 'Kids')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='category',
            field=models.CharField(blank=True, choices=[('CIRCULAR_KNIT', 'Circular Knit'), ('FLAT_KNIT', 'Flat Knit'), ('WOVEN', 'Woven')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('MENS', 'Mens'), ('JR_LADIES', 'Jr. Ladies'), ('WOMEN', 'Women'), ('JUNIOR_BOYS', 'Junior Boys'), ('SENIOR_BOYS', 'Senior Boys'), ('TODDLER_BOYS', 'Toddler Boys'), ('JUNIOR_GIRLS', 'Junior Girls'), ('SENIOR_GIRLS', 'Senior Girls'), ('TODDLER_GIRLS', 'Toddler Girls'), ('KIDS', 'Kids')], max_length=20, null=True),
        ),
    ]
