# Generated by Django 5.2.7 on 2025-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_manager', '0004_garmentsample_category_garmentsample_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentsample',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgarmentsample',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
