# Generated by Django 5.2.7 on 2025-12-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_manager', '0005_alter_garmentsample_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentsample',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('MENS', 'Mens'), ('JR_LADIES', 'Jr. Ladies'), ('WOMEN', 'Women'), ('JUNIOR_BOYS', 'Junior Boys'), ('SENIOR_BOYS', 'Senior Boys'), ('TODDLER_BOYS', 'Toddler Boys'), ('JUNIOR_GIRLS', 'Junior Girls'), ('SENIOR_GIRLS', 'Senior Girls'), ('TODDLER_GIRLS', 'Toddler Girls'), ('KIDS', 'Kids'), ('DENIM', 'Denim'), ('NON_DENIM', 'Non Denim')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgarmentsample',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('MENS', 'Mens'), ('JR_LADIES', 'Jr. Ladies'), ('WOMEN', 'Women'), ('JUNIOR_BOYS', 'Junior Boys'), ('SENIOR_BOYS', 'Senior Boys'), ('TODDLER_BOYS', 'Toddler Boys'), ('JUNIOR_GIRLS', 'Junior Girls'), ('SENIOR_GIRLS', 'Senior Girls'), ('TODDLER_GIRLS', 'Toddler Girls'), ('KIDS', 'Kids'), ('DENIM', 'Denim'), ('NON_DENIM', 'Non Denim')], max_length=20, null=True),
        ),
    ]
