# Generated by Django 5.2.7 on 2025-12-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_manager', '0006_alter_garmentsample_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentsample',
            name='weight_type',
            field=models.CharField(blank=True, choices=[('GM', 'Gm'), ('KG', 'Kg'), ('GSM', 'GSM')], default='GM', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgarmentsample',
            name='weight_type',
            field=models.CharField(blank=True, choices=[('GM', 'Gm'), ('KG', 'Kg'), ('GSM', 'GSM')], default='GM', max_length=20, null=True),
        ),
    ]
