# Generated by Django 5.2.7 on 2026-01-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_manager', '0007_alter_garmentsample_weight_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garmentsample',
            name='gsm',
        ),
        migrations.RemoveField(
            model_name='garmentsample',
            name='size',
        ),
        migrations.RemoveField(
            model_name='garmentsample',
            name='size_cen',
        ),
        migrations.RemoveField(
            model_name='garmentsample',
            name='size_range',
        ),
        migrations.RemoveField(
            model_name='garmentsample',
            name='size_type',
        ),
        migrations.RemoveField(
            model_name='historicalgarmentsample',
            name='gsm',
        ),
        migrations.RemoveField(
            model_name='historicalgarmentsample',
            name='size',
        ),
        migrations.RemoveField(
            model_name='historicalgarmentsample',
            name='size_cen',
        ),
        migrations.RemoveField(
            model_name='historicalgarmentsample',
            name='size_range',
        ),
        migrations.RemoveField(
            model_name='historicalgarmentsample',
            name='size_type',
        ),
        migrations.AddField(
            model_name='garmentsample',
            name='age_range_month_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garmentsample',
            name='age_range_month_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garmentsample',
            name='age_range_year_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garmentsample',
            name='age_range_year_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garmentsample',
            name='letter_range_max',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='garmentsample',
            name='letter_range_min',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='garmentsample',
            name='size_range_type',
            field=models.CharField(choices=[('LETTER_RANGE', 'Letter Range'), ('AGE_RANGE_YEAR', 'Age Range Year'), ('AGE_RANGE_MONTH', 'Age Range Month')], default='LETTER_RANGE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='age_range_month_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='age_range_month_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='age_range_year_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='age_range_year_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='letter_range_max',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='letter_range_min',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalgarmentsample',
            name='size_range_type',
            field=models.CharField(choices=[('LETTER_RANGE', 'Letter Range'), ('AGE_RANGE_YEAR', 'Age Range Year'), ('AGE_RANGE_MONTH', 'Age Range Month')], default='LETTER_RANGE', max_length=20),
        ),
    ]
