# Generated by Django 5.2.7 on 2026-01-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_manager', '0008_remove_garmentsample_gsm_remove_garmentsample_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentsample',
            name='letter_range_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='garmentsample',
            name='letter_range_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgarmentsample',
            name='letter_range_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgarmentsample',
            name='letter_range_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
